id: 93de78f3b376484a85d29a71b6e40d64
initial_creation_type: ocr
source_metadata:
  volumes:
    b72be89f6c6d4b4a964482bdc427b91b:
      base_file: v022.txt
      image_group_id: I1PD95867
      title: དཔལ་གསང་བ་འདུས་པ་འཇིག་རྟེན་དབང་ཕྱུག་གི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1409
      volume_number: 22
