id: D83213C15
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:31:36+00:00'
last_modified: '2022-05-26T10:31:23.438503+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d065:
      image_group_id: I1PD95867
      title: དཔལ་གསང་བ་འདུས་པ་འཇིག་རྟེན་དབང་ཕྱུག་གི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1409
      order: 22
      base_file: d065.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
